FROM dockerfactory.rsglab.com/@@PARENTIMAGE@@:@@PARENTIMAGEVERSION@@

ENV LANG en_US.utf8
ENV LC_ALL en_US.utf8
ENV PATH /usr/local/pyenv/shims:$PATH

COPY ./expire.py /root/expire.py
COPY ./requirements.txt /tmp/requirements.txt 
RUN pip install -r /tmp/requirements.txt

WORKDIR /root

VOLUME "/root/config.yaml"

ENTRYPOINT ["python", "/root/expire.py"]
CMD ["/root/config.yaml"]
